In [1]:
import numpy as np

In [74]:
def SVD(m=4,n=3):
    random_matrix = np.random.randint(1,10,(m,n))
    #random_matrix = np.identity(n)
    U,diag,V_T = np.linalg.svd(random_matrix)
    print("U svd:",U)
    print("Diag svd:",diag)
    print("V.T svd:",V_T)
    print("********************")
    print("Random Matrix :",random_matrix)

    temp1 = np.matmul(random_matrix.T,random_matrix)
    
    lambda_,V = np.linalg.eig(temp1)
    #U=U.T
    print("lambda: ",lambda_) 
    sorted_lambda = np.sort(lambda_)[::-1]
    print("Lambda sorted :   ",sorted_lambda)
    
    idx = np.argsort(lambda_)[::-1]
    print("idx",idx)
    
#     V_sort = np.zeros_like(V)
    V_sort = V.copy()
      
    #print("V: ",V)
#     _,c = V_sort.shape
#     for i in range(c):
#         V_sort[:,i] = V[:,idx[i]]/np.sqrt(np.sum(np.square(V[:,idx[i]])))

    print("V sorted: ",V_sort.T)

    
    U_sort = np.matmul(random_matrix,V_sort)
    _,c = U_sort.shape
    for i in range(c):
        U_sort[:,i] = U_sort[:,i]/np.sqrt(np.sum(np.square(U_sort[:,i])))

    print("U_sort: ",U_sort)
    
    print("*****************************************")
    print("calculated matrix: \n",np.matmul(np.matmul(U_sort,np.diag(np.sqrt(sorted_lambda))),V_sort.T))
    


#if __name__=="__main__":
#    SVD()

In [75]:
SVD()

U svd: [[-0.49379627  0.03795083  0.0885061  -0.86422893]
 [-0.5646277  -0.50999126 -0.60354463  0.23840798]
 [-0.26904848  0.85695695 -0.41356403  0.14900499]
 [-0.60413055  0.06397995  0.67591815  0.41721397]]
Diag svd: [16.44602601  2.75590304  2.22108686]
V.T svd: [[-0.62721578 -0.59367238 -0.50413636]
 [-0.7762784   0.42400607  0.46648761]
 [-0.06318393  0.68393856 -0.72679835]]
********************
Random Matrix : [[5 5 4]
 [7 4 5]
 [1 3 4]
 [6 7 4]]
lambda:  [270.47177158   7.59500156   4.93322685]
Lambda sorted :    [270.47177158   7.59500156   4.93322685]
idx [0 1 2]
V sorted:  [[ 0.62721578  0.59367238  0.50413636]
 [ 0.7762784  -0.42400607 -0.46648761]
 [ 0.06318393 -0.68393856  0.72679835]]
U_sort:  [[ 0.49379627 -0.03795083 -0.0885061 ]
 [ 0.5646277   0.50999126  0.60354463]
 [ 0.26904848 -0.85695695  0.41356403]
 [ 0.60413055 -0.06397995 -0.67591815]]
*****************************************
calculated matrix: 
 [[5. 5. 4.]
 [7. 4. 5.]
 [1. 3. 4.]
 [6. 7. 4.]]


In [28]:
import numpy as np

#A = np.array([[0, 1, 1], [2**0.5, 2, 0], [0, 1, 1]]) #np.array([[1, 1, 0, 1], [0, 0, 0, 1], [1, 1, 0,0]])#np.array([[1, 2], [2, 1]])#np.array([[1, 1, 1, 0], [0, 1, 0, 1]])
A = np.random.randn(4,4)
print(A)

eigvals_p, eigvecs_p = np.linalg.eigh(np.dot(A, A.T)) #P
#unit normalize eigvecs1
temp_eigvecs_p = []
for ele in eigvecs_p.T: #take each column and unit normalize
	temp_eigvecs_p.append(ele/float(sum(ele**2)**0.5))
	
eigvecs_p = np.column_stack((temp_eigvecs_p))

#computing eigen vectors of Q matrix
eigvecs_q = []
#print("Eig val of P ",eigvals_p)
for index, ele in enumerate(eigvals_p):
	#print(ele)
	if ele != 0:
		eigvecs_q.append(np.dot(A.T, eigvecs_p.T[index])/(float(abs(ele)**0.5)))
		
		
P = eigvecs_p
S = np.diag(abs(eigvals_p)**0.5)
Q = np.column_stack((eigvecs_q))	
print("Left Singular Vectors!")
print(P)
print("Singular Values!")
print(S)
print("Right Singular Vectors!")
print(Q)

M = np.dot(np.dot(P,S), Q.T)
print("Approximated matrix!")
print(M)




[[ 0.57035095 -0.81203493 -0.39437106 -0.32835625]
 [-1.62884067 -0.65584528  0.55322133  1.0375935 ]
 [ 0.53815094  0.16845383 -0.25418855  0.85647695]
 [-0.58525425 -0.36832146  0.68413383  0.13594493]]
Left Singular Vectors!
[[-0.00835334 -0.87723028  0.41896402 -0.23423578]
 [-0.33696172 -0.27785349 -0.08795684  0.89527528]
 [ 0.31828073 -0.3906008  -0.85950802 -0.08587412]
 [ 0.88604988  0.026372    0.2792467   0.36910893]]
Singular Values!
[[0.39994522 0.         0.         0.        ]
 [0.         0.97525917 0.         0.        ]
 [0.         0.         1.11271255 0.        ]
 [0.         0.         0.         2.33357914]]
Right Singular Vectors!
[[ 0.49209547 -0.28032197 -0.21906032 -0.79452767]
 [-0.11240945  0.83983723 -0.47646385 -0.23456286]
 [ 0.85550039  0.31742125  0.1758157   0.36939365]
 [ 0.11543501 -0.33961268 -0.83311681  0.42101588]]
Approximated matrix!
[[ 0.57035095 -0.81203493 -0.39437106 -0.32835625]
 [-1.62884067 -0.65584528  0.55322133  1.0375935 ]
 [ 0.5381