In [1]:
import numpy as np

In [30]:
def SVD(m=4,n=4):
    random_matrix = np.random.randint(1,10,(m,n))
    #random_matrix = np.identity(n)
    U,diag,V_T = np.linalg.svd(random_matrix)
    print("U svd:",U)
    print("Diag svd:",diag)
    print("V.T svd:",V_T)
    print("********************")
    print("Random Matrix :",random_matrix)

    temp1 = np.matmul(random_matrix,random_matrix.T)
    
    lambda_,U = np.linalg.eig(temp1)
    #U=U.T
    print("lambda: ",lambda_) 
    sorted_lambda = np.sort(lambda_)[::-1]
    print("Lambda sorted :   ",sorted_lambda)
    
    idx = np.argsort(lambda_)[::-1]
    print("idx",idx)
    
    U_sort = np.zeros_like(U)

    print("U: ",U)
    _,c = U_sort.shape
    for i in range(c):
        U_sort[:,i] = U[:,idx[i]]/np.sqrt(np.sum(np.square(U[:,idx[i]])))

    print("U sorted: ",U_sort)
    
    #idx = np.argsort(lambda_)
    #U_sort = np.take_along_axis(U,idx,axis=0)
    
    temp2 = np.matmul(random_matrix.T,random_matrix)
    
    lambda_,V = np.linalg.eig(temp2)
    #V=V.T
    print("lambda: ",lambda_) 
    sorted_lambda = np.sort(lambda_)[::-1]
    idx_ = np.argsort(lambda_)[::-1]
    print("idx",idx_)
    V_sort = np.zeros_like(V)
    
    print("V: ",V)
    _,c = V_sort.shape
    for i in range(c):
        V_sort[:,i] = V[:,idx_[i]]/np.sqrt(np.sum(np.square(V[:,idx[i]])))

    print("Lambda sorted :",sorted_lambda)
    print("V_sort_T: ",V_sort.T)
    
    print("*****************************************")
    print("calculated matrix: \n",np.matmul(np.matmul(U_sort,np.diag(np.sqrt(sorted_lambda))),V_sort.T))
    


#if __name__=="__main__":
#    SVD()

In [31]:
SVD()

U svd: [[-0.59722665 -0.15396315  0.44423125 -0.64982634]
 [-0.57068697 -0.56383559 -0.10226393  0.58817336]
 [-0.49050836  0.46864373 -0.71886956 -0.15166132]
 [-0.27755765  0.66238798  0.52481162  0.45692087]]
Diag svd: [21.13763436  7.98656671  3.78962245  1.74754897]
V.T svd: [[-0.41757577 -0.45870581 -0.54418206 -0.56487639]
 [ 0.90228727 -0.10942326 -0.27207532 -0.31603678]
 [-0.1062412   0.83320769 -0.06109676 -0.5392077 ]
 [-0.01486453  0.28875678 -0.79126992  0.53878612]]
********************
Random Matrix : [[4 7 8 6]
 [1 6 7 9]
 [8 2 5 6]
 [7 4 1 1]]
lambda:  [  3.05392741  14.36123828  63.78524778 446.79958654]
Lambda sorted :    [446.79958654  63.78524778  14.36123828   3.05392741]
idx [3 2 1 0]
U:  [[-0.64982634 -0.44423125  0.15396315 -0.59722665]
 [ 0.58817336  0.10226393  0.56383559 -0.57068697]
 [-0.15166132  0.71886956 -0.46864373 -0.49050836]
 [ 0.45692087 -0.52481162 -0.66238798 -0.27755765]]
U sorted:  [[-0.59722665  0.15396315 -0.44423125 -0.64982634]
 [-0.570686

In [28]:
import numpy as np

#A = np.array([[0, 1, 1], [2**0.5, 2, 0], [0, 1, 1]]) #np.array([[1, 1, 0, 1], [0, 0, 0, 1], [1, 1, 0,0]])#np.array([[1, 2], [2, 1]])#np.array([[1, 1, 1, 0], [0, 1, 0, 1]])
A = np.random.randn(4,4)
print(A)

eigvals_p, eigvecs_p = np.linalg.eigh(np.dot(A, A.T)) #P
#unit normalize eigvecs1
temp_eigvecs_p = []
for ele in eigvecs_p.T: #take each column and unit normalize
	temp_eigvecs_p.append(ele/float(sum(ele**2)**0.5))
	
eigvecs_p = np.column_stack((temp_eigvecs_p))

#computing eigen vectors of Q matrix
eigvecs_q = []
#print("Eig val of P ",eigvals_p)
for index, ele in enumerate(eigvals_p):
	#print(ele)
	if ele != 0:
		eigvecs_q.append(np.dot(A.T, eigvecs_p.T[index])/(float(abs(ele)**0.5)))
		
		
P = eigvecs_p
S = np.diag(abs(eigvals_p)**0.5)
Q = np.column_stack((eigvecs_q))	
print("Left Singular Vectors!")
print(P)
print("Singular Values!")
print(S)
print("Right Singular Vectors!")
print(Q)

M = np.dot(np.dot(P,S), Q.T)
print("Approximated matrix!")
print(M)




[[ 0.57035095 -0.81203493 -0.39437106 -0.32835625]
 [-1.62884067 -0.65584528  0.55322133  1.0375935 ]
 [ 0.53815094  0.16845383 -0.25418855  0.85647695]
 [-0.58525425 -0.36832146  0.68413383  0.13594493]]
Left Singular Vectors!
[[-0.00835334 -0.87723028  0.41896402 -0.23423578]
 [-0.33696172 -0.27785349 -0.08795684  0.89527528]
 [ 0.31828073 -0.3906008  -0.85950802 -0.08587412]
 [ 0.88604988  0.026372    0.2792467   0.36910893]]
Singular Values!
[[0.39994522 0.         0.         0.        ]
 [0.         0.97525917 0.         0.        ]
 [0.         0.         1.11271255 0.        ]
 [0.         0.         0.         2.33357914]]
Right Singular Vectors!
[[ 0.49209547 -0.28032197 -0.21906032 -0.79452767]
 [-0.11240945  0.83983723 -0.47646385 -0.23456286]
 [ 0.85550039  0.31742125  0.1758157   0.36939365]
 [ 0.11543501 -0.33961268 -0.83311681  0.42101588]]
Approximated matrix!
[[ 0.57035095 -0.81203493 -0.39437106 -0.32835625]
 [-1.62884067 -0.65584528  0.55322133  1.0375935 ]
 [ 0.5381